export const SEPAY_ERROR_CODES = {
  API_ERROR: 'SEPAY_API_ERROR',
  TOKEN_ERROR: 'SEPAY_TOKEN_ERROR',
  INVALID_TOKEN_RESPONSE: 'SEPAY_INVALID_TOKEN_RESPONSE',
  AUTH_FAILED: 'SEPAY_AUTH_FAILED',
  CONFIG_REQUIRED: 'SEPAY_CONFIG_REQUIRED',
  INVALID_TEMPLATE_SERIES: 'SEPAY_INVALID_TEMPLATE_SERIES',
  DRAFT_NOT_READY: 'SEPAY_DRAFT_NOT_READY',
  INVOICE_NOT_FOUND: 'SEPAY_INVOICE_NOT_FOUND',
  DOWNLOAD_NOT_READY: 'SEPAY_DOWNLOAD_NOT_READY',
  TEMPLATE_VALIDATION_FAILED: 'SEPAY_TEMPLATE_VALIDATION_FAILED',
  CREATE_NO_TRACKING: 'SEPAY_CREATE_NO_TRACKING',
  CREATE_POLL_FAILED: 'SEPAY_CREATE_POLL_FAILED',
  ISSUE_NO_TRACKING: 'SEPAY_ISSUE_NO_TRACKING',
  ISSUE_POLL_FAILED: 'SEPAY_ISSUE_POLL_FAILED',
  REFRESH_CREATE_FAILED: 'SEPAY_REFRESH_CREATE_FAILED',
  REFRESH_ISSUE_FAILED: 'SEPAY_REFRESH_ISSUE_FAILED',
} as const;

export type SepayErrorCode = typeof SEPAY_ERROR_CODES[keyof typeof SEPAY_ERROR_CODES];

export class SepayError extends Error {
  constructor(
    message: string,
    public readonly statusCode: number,
    public readonly code: SepayErrorCode = SEPAY_ERROR_CODES.API_ERROR,
    public readonly details?: unknown
  ) {
    super(message);
    this.name = 'SepayError';
  }
}
